# Generated by Django 3.2.5 on 2021-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(default='nоt define', max_length=120)),
                ('text_message', models.CharField(default='nоt define', max_length=200)),
                ('array', models.CharField(default='nоt define', max_length=200)),
                ('text_nnn', models.CharField(default='nоt define', max_length=200)),
                ('halfstarsInput', models.CharField(default='nоt define', max_length=120)),
                ('docId_user', models.CharField(default='nоt define', max_length=120)),
                ('user_browser', models.CharField(default='nоt define', max_length=120)),
                ('user_device', models.CharField(default='nоt define', max_length=120)),
                ('city', models.CharField(default='nоt define', max_length=120)),
                ('date', models.CharField(default='nоt define', max_length=120)),
                ('service_name', models.CharField(default='nоt define', max_length=120)),
            ],
        ),
    ]
