# Generated by Django 3.2.5 on 2021-07-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='ReviewForm',
        ),
    ]
