# Generated by Django 3.2.5 on 2021-07-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review_form', '0002_rename_contactform_reviewform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewform',
            old_name='city',
            new_name='region',
        ),
    ]
